/**
 * Gemeinsame Sperrliste für Backend und Frontend.
 * Produkte mit diesen Mustern werden nicht angeboten.
 */

export const BLOCKED_ID_PATTERNS = [
  'esim',
  'sim-card',
  'prepaid-visa',
  'prepaid-mastercard',
  'virtual-card',
  'visa-card',
  'mastercard-card',
  'bill-pay',
  'billpay',
  'utility',
  'gambling',
  'casino',
  'betting',
  'adult',
  'onlyfans',
  'porn',
  'paysafecard',
  'paysafe',
  'moneygram',
  'western-union',
  'crypto',
  'bitcoin-card',
  'tobacco',
  'cigarette',
  'vape',
  'nicotine',
  'weapon',
  'gun',
  'cash-out',
  'cashout',
  'money-transfer',
  'gift-of-choice',
  'anonymous-prepaid',
  'dating',
  'hookup',
  'tinder',
];

export const BLOCKED_CATEGORY_KEYWORDS = [
  'esim',
  'refill',
  'bill',
  'utility',
  'gambling',
  'casino',
  'betting',
  'adult',
  'prepaid card',
  'virtual card',
  'payment card',
  'telecom',
  'mobile top',
  'cryptocurrency',
  'money transfer',
  'tobacco',
  'nicotine',
  'weapon',
  'anonymous',
  'dating',
  'hookup',
];
