/** Kuratierte beliebte Gutscheine pro Land (Bitrefill product IDs). */
export const POPULAR_BY_COUNTRY = {
  DE: [
    'amazon_de-germany',
    'tiktok-coins-germany',
    'google-play-germany',
    'itunes-germany',
    'netflix-eu',
    'steam-eur-international',
    'playstation-pin-germany',
    'nintendo-germany',
    'rewe-germany',
    'kaufland-germany',
    'media-markt-germany',
    'zalando-germany',
    'lieferando-germany',
    'ikea-germany',
    'douglas-germany',
    'saturn-germany',
    'xbox-germany',
    'roblox-european-union',
    'lego-germany',
    'dazn-germany',
    'hellofresh-germany',
    'adidas-de',
    'intersport-germany',
    'mydays-de',
    'canda-pin-germany',
  ],
  AT: [
    'amazon-at-austria',
    'tiktok-coins-austria',
    'google-play-austria',
    'apple-austria',
    'netflix-eu',
    'zalando-austria',
    'media-markt-austria',
    'ikea-at',
    'jochen-schweizer-at',
    'nintendo-austria',
    'playstation-austria',
  ],
  CH: [
    'amazon-ch-switzerland',
    'tiktok-coins-switzerland',
    'google-play-switzerland',
    'apple-switzerland',
    'netflix-switzerland',
    'zalando-ch',
    'manor-switzerland',
    'coop-switzerland',
    'just-eat-switzerland',
    'nintendo-switzerland',
    'psn-switzerland',
  ],
  US: [
    'amazon_com-usa',
    'tiktok-coins-usa',
    'google-play-usa',
    'apple-usa',
    'steam-usa',
    'xbox-usa',
    'playstation-usa',
    'netflix-usa',
    'spotify-usa',
    'uber-usa',
    'doordash-usa',
    'target-usa',
    'walmart-usa',
    'starbucks-usa',
    'disney-usa',
    'roblox-usa',
    'chipotle-usa',
    'nike-usa',
  ],
  GB: [
    'amazon-uk',
    'tiktok-coins-united-kingdom',
    'google-play-united-kingdom',
    'steam-united-kingdom',
    'netflix-united-kingdom',
    'spotify-united-kingdom',
    'xbox-united-kingdom',
    'playstation-united-kingdom',
    'uber-united-kingdom',
    'tesco-uk',
    'currys-uk',
    'primark-uk',
    'nike-uk',
  ],
  FR: [
    'amazon-france',
    'tiktok-coins-france',
    'google-play-france',
    'netflix-france',
    'spotify-france',
    'steam-france',
    'uber-france',
    'fnac-france',
    'decathlon-france',
    'zalando-france',
    'sephora-france',
  ],
  NL: [
    'amazon-nl-netherlands',
    'tiktok-coins-netherlands',
    'bol-com-netherlands',
    'zalando-netherlands',
    'coolblue-nl',
    'netflix-netherlands',
  ],
  ES: [
    'amazon-es-spain',
    'tiktok-live-tarjeta-regalo-spain',
    'netflix-spain',
    'zalando-spain',
    'media-markt-spain',
  ],
  IT: [
    'amazon-it-italy',
    'tiktok-coins-italy',
    'netflix-italy',
    'zalando-italy',
    'sephora-italy',
  ],
};

export function getPopularIds(country) {
  return POPULAR_BY_COUNTRY[country] || POPULAR_BY_COUNTRY.DE;
}
